# Type Path Mode User Group Age Argument
d /run/binnacle-privileged 0750 root binnacle-privileged-client -
d /var/lib/binnacle-privileged 0700 root root -
d /etc/binnacle-privileged 0700 root root -
d /opt/binnacle-privileged 0755 root root -
