"""Retained payload byte/metadata boundary."""

from __future__ import annotations

from typing import Protocol

from binnacle.domain.payload import PayloadMetadata


class PayloadStore(Protocol):
    async def create(self, metadata: PayloadMetadata) -> PayloadMetadata: ...

    async def append(self, payload_id: str, chunk: bytes) -> PayloadMetadata: ...

    async def finalize(self, payload_id: str) -> PayloadMetadata: ...

    async def read_range(self, payload_id: str, start: int, end: int) -> bytes: ...

    async def verify(self, payload_id: str) -> PayloadMetadata: ...


class PayloadMetadataRepository(Protocol):
    async def create(self, metadata: PayloadMetadata) -> None: ...

    async def get(self, payload_id: str) -> PayloadMetadata | None: ...

    async def list_all(self) -> tuple[PayloadMetadata, ...]: ...

    async def update_building_size(self, payload_id: str, byte_count: int) -> PayloadMetadata: ...

    async def complete(
        self, payload_id: str, *, byte_count: int, sha256: str
    ) -> PayloadMetadata: ...

    async def fail(self, payload_id: str) -> PayloadMetadata: ...

    async def controller_bytes(self, controller_id: str, controller_epoch: int) -> int: ...
